### ISSUE TITLE
python3.5.2 运行的时候有问题

### ISSUE THREAD

**Issue by hongyinjie** [rockingdingo/deepnlp#15]
运行这个 python3 test/test_segment.py   
会有异常：
Traceback (most recent call last):
  File "test/test_segment.py", line 7, in <module>
    segList = segmenter.seg(text)
  File "/usr/local/lib/python3.5/dist-packages/deepnlp/segmenter.py", line 28, in seg
    model.add((char + "\to\tB").encode('utf-8'))
  File "/usr/local/lib/python3.5/dist-packages/CRFPP.py", line 101, in add
    def add(self, *args): return _CRFPP.Tagger_add(self, *args)
TypeError: in method 'Tagger_add', argument 2 of type 'char const *'

但是我同样的方法，换成py27 就是正常了。

**Comment by zhangxuelai** [comment]
@hongyinjie  你问题解决了吗？

**Comment by lightjake** [comment]
把.encode('utf-8'))去掉

**Comment by qxde01** [comment]
python3.4 也有这个问题

**Comment by hongyinjie** [comment]
.encode('utf-8'))
.decode('utf-8'))
去掉之后， 可以运行了

**Comment by hongyinjie** [comment]
其他兼容性，还有问题。
tensorflow 只支持1.0.1， 不支持1.1.0

**Comment by rockingdingo** [comment]
@hongyinjie @qxde01 @lightjake @zhangxuelai  多谢帮助留意，最近一直很忙没有时间更新和修改，下一版我会修正的，另外正在测试tensorflow 1.2 的API。

**Comment by lstmabc** [comment]
你好，我也是这个问题，不知道怎么解决，可以把正确的代码贴出来吗？

**Comment by lstmabc** [comment]
@rockingdingo 有没有微信？非常感谢你无私的奉献。
