### ISSUE TITLE
POS tagging

### ISSUE THREAD

**Issue by altangadas** [rockingdingo/deepnlp#18]
你好！我想用你的代码训练其他语言的Pos tagger，出现了以下错误。
Epoch: 1 Learning rate: 0.100
Traceback (most recent call last):
  File "pos_model.py", line 285, in <module>
    tf.app.run()
  File "/Users/Altangadas/.pyenv/versions/anaconda3-4.3.0/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "pos_model.py", line 276, in main
    verbose=True)
  File "pos_model.py", line 225, in run_epoch
    if verbose and step % (epoch_size // 10) == 10:
ZeroDivisionError: integer division or modulo by zero

是因为训练语料（train.txt)太小吗？
请指教。

**Comment by kuoyliu** [comment]
Do you know what is dev.txt? thx!!!
